### ISSUE TITLE
Error using Dynamo.xmi in ArgoUML

### ISSUE THREAD

**Issue by oenone** [stcarrez/dynamo#2]
Adding the uml path of the dynamo installation to the profiles in ArgoUML generates FileNotFound errors. It seems like the referenced URL "http://argouml.org/user-profiles/Dynamo.xmi" results in a 404 error.

Complete error:
```
org.argouml.model.XmiReferenceRuntimeException: http://argouml.org/user-profiles/Dynamo.xmi                                                                                             
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.endElement(XmiSAXReader.java:258)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
        at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
        at org.argouml.profile.URLModelLoader.loadModel(URLModelLoader.java:99)
        at org.argouml.profile.FileModelLoader.loadModel(FileModelLoader.java:63)
        at org.argouml.profile.UserDefinedProfile.loadModel(UserDefinedProfile.java:322)
        at org.argouml.profile.UserDefinedProfile.getProfilePackages(UserDefinedProfile.java:745)
        at org.argouml.profile.UserDefinedProfile.getAllCritiquesInModel(UserDefinedProfile.java:664)
        at org.argouml.profile.UserDefinedProfile.getCritics(UserDefinedProfile.java:449)
        at org.argouml.profile.internal.ProfileManagerImpl.registerProfileInternal(ProfileManagerImpl.java:290)
        at org.argouml.profile.internal.ProfileManagerImpl.access$100(ProfileManagerImpl.java:71)
        at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:151)
        at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:144)
        at org.argouml.profile.internal.DependencyResolver.internalResolve(DependencyResolver.java:114)
        at org.argouml.profile.internal.DependencyResolver.resolve(DependencyResolver.java:83)
        at org.argouml.profile.internal.ProfileManagerImpl.loadProfiles(ProfileManagerImpl.java:413)
        at org.argouml.profile.internal.ProfileManagerImpl.refreshRegisteredProfiles(ProfileManagerImpl.java:408)
        at org.argouml.profile.internal.ProfileManagerImpl.<init>(ProfileManagerImpl.java:138)
        at org.argouml.profile.init.InitProfileSubsystem.init(InitProfileSubsystem.java:64)
        at org.argouml.application.Main.initializeSubsystems(Main.java:425)
        at org.argouml.application.Main.main(Main.java:189)
Caused by: org.argouml.model.XmiException: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:352)
        at org.argouml.model.mdr.XmiReferenceResolverImpl.readExternalDocument(XmiReferenceResolverImpl.java:644)
        ... 37 more
Caused by: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:676)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
        at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
        ... 38 more
[org.netbeans.lib.jmi.Logger] XMI parsing error at line: 18026: http://argouml.org/user-profiles/Dynamo.xmi
```

**Comment by stcarrez** [comment]
Ah yes, each time I have to re-setup ArgoUML, I reach this kind of issue. Annoying...

I have this article which also describes this:

https://blog.vacs.fr/vacs/blogs/tagged.html?tag=UML

The issue is to re-start ArgoUML at different steps of the process :-)

1.  Select and add a directory that contains the UML profiles (Edit -> Settings -> Profile -> Add)
2. Verify that the new directory appears in the directory list in Edit -> Settings -> Profile -> Add dialog
3. Re-start Argo-UML
4. Go again in Edit -> Settings -> Profile -> Add
5. The directory you added should still be there in the Add dialog. You should see there (on the left) the Dynamo.xmi UML profile. Click on ">>" to activate it.
6. Re-start Argo-UML
7. At this step, you should see Dynamo.xmi in the ProfileConfiguration

Alternatively you can check the file `~/.argouml/argo.user.properties`, it should contain something like:


  argo.profiles.default=CUML 1.4*CGoodPractices*CCodeGeneration*Ufile\:/build/local-gnat-2019/share/dynamo/base/uml/Dynamo.xmi*
  argo.profiles.directories=/build/local-gnat-2019/share/dynamo/base/uml*

May be you can edit the ArgoUML configuration file manually and update/add the two above properties after updating your installation path.

>

**Comment by oenone** [comment]
I tried it, but as soon as i restart ArgoUML after adding the profile directory, it outputs the error while starting. It continues to start, and can use the data types and stereotypes defined by Dynamo.xmi.

But when I try to add AWA.xmi, it appears empty:
![image](https://user-images.githubusercontent.com/437919/76349316-0c92ee00-630a-11ea-8ca0-5c3065d876d8.png)

Any idea how to fix this? Should I post this in the AWA repository instead?

When I remove all references to `http://argouml.org/user-profiles/Dynamo.xmi#...` in both .xmi files, ArgoUML starts without error and shows the content of the AWA profile - but with missing stereotypes, tags, etc from Dynamo.

**Comment by stcarrez** [comment]
Your Dynamo profile looks correct. The AWA profile should not be empty and should contain the AWA package with all data model types provided by AWA.

Can you verify the sha1sum of both xmi files?
You should get:

```
571fc5ceda2001e93c2967d04905bc8d8b90fa24  AWA.xmi
6b413c9863fb63c255e6abc5de31ff9902955c77  Dynamo.xmi
```

Which version of ArgoUML are you using?

I'm using ArgoUML 0.35.1 but I've also checked that 0.34 works very well.

Can you verify that, at the time you launch ArgoUML, your Internet connection is functional?
This is weird but ArgoUML needs the Internet access even though the AWA and Dynamo XMI
profiles are not downloaded.

You should not have to modify the AWA.xmi nor the Dynamo.xmi files.

Can you include the full output produced by ArgoUML?

I will need the full output to have a better idea of your problem.

**Comment by oenone** [comment]
Here the sha1sums of my files:
```
571fc5ceda2001e93c2967d04905bc8d8b90fa24  /home/oenone/Programme/GNAT/2019/share/dynamo/base/uml/AWA.xmi
6b413c9863fb63c255e6abc5de31ff9902955c77  /home/oenone/Programme/GNAT/2019/share/dynamo/base/uml/Dynamo.xmi
```

I use ArgoUML 0.34, and my internet connection is stable and functional.

If the dynamo uml directory is present in the default XMI directories, I get this exact error on the terminal I start ArgoUML:
```
$ ./argouml.sh                                                                                                                                                               
log4j:WARN No such property [follow] in org.apache.log4j.ConsoleAppender.                                                                                                               
org.argouml.model.XmiReferenceRuntimeException: http://argouml.org/user-profiles/Dynamo.xmi                                                                                             
        at org.netbeans.lib.jmi.xmi.XmiContext.resolveExternalReferences(XmiContext.java:839)
        at org.netbeans.lib.jmi.xmi.XmiElement$Content.endElement(XmiElement.java:394)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.endElement(XmiSAXReader.java:258)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
        at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
        at org.argouml.profile.URLModelLoader.loadModel(URLModelLoader.java:99)
        at org.argouml.profile.FileModelLoader.loadModel(FileModelLoader.java:63)
        at org.argouml.profile.UserDefinedProfile.loadModel(UserDefinedProfile.java:322)
        at org.argouml.profile.UserDefinedProfile.getProfilePackages(UserDefinedProfile.java:745)
        at org.argouml.profile.UserDefinedProfile.getAllCritiquesInModel(UserDefinedProfile.java:664)
        at org.argouml.profile.UserDefinedProfile.getCritics(UserDefinedProfile.java:449)
        at org.argouml.profile.internal.ProfileManagerImpl.registerProfileInternal(ProfileManagerImpl.java:290)
        at org.argouml.profile.internal.ProfileManagerImpl.access$100(ProfileManagerImpl.java:71)
        at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:151)
        at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:144)
        at org.argouml.profile.internal.DependencyResolver.internalResolve(DependencyResolver.java:114)
        at org.argouml.profile.internal.DependencyResolver.resolve(DependencyResolver.java:83)
        at org.argouml.profile.internal.ProfileManagerImpl.loadProfiles(ProfileManagerImpl.java:413)
        at org.argouml.profile.internal.ProfileManagerImpl.refreshRegisteredProfiles(ProfileManagerImpl.java:408)
        at org.argouml.profile.internal.ProfileManagerImpl.<init>(ProfileManagerImpl.java:138)
        at org.argouml.profile.init.InitProfileSubsystem.init(InitProfileSubsystem.java:64)
        at org.argouml.application.Main.initializeSubsystems(Main.java:425)
        at org.argouml.application.Main.main(Main.java:189)
Caused by: org.argouml.model.XmiException: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:352)
        at org.argouml.model.mdr.XmiReferenceResolverImpl.readExternalDocument(XmiReferenceResolverImpl.java:644)
        ... 37 more
Caused by: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:676)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
        at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
        at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
        at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
        ... 38 more
[org.netbeans.lib.jmi.Logger] XMI parsing error at line: 18026: http://argouml.org/user-profiles/Dynamo.xmi
```

I just tried out removing the directory from the default XMI directories, after adding the Dynamo.xmi and AWA.xmi to the default profiles, and now it starts without the error message. The content of the AWA profile is shown, too, and the classes have the expected stereotypes, tags, etc.

So, the problem only exists for me when dynamo's uml directory is set as default XMI directory. I can work with it now. maybe it helps you locate the reason - if you need any more information, let me know how to provide them.

**Comment by stcarrez** [comment]
Good to know it works now.

I tried again against a fresh installation but I wasn't able to reproduce.
On my side, I still have the dynamo's UML directory set in ArgoUML.
That's an ArgoUML issue.

Feel free to report issues or ask questions, I'll tried to help as much as possible.

**Comment by oenone** [comment]
Ok, thanks. I will do a bit more research and file an issue to ArgoUML.
